name: Standart Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Check wokeness
      uses: get-woke/woke-action@v0
      with:
        # Cause the check to fail on any broke rules
        fail-on-error: true

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test Backend
      run: go test -v ./...

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Test Frontend
      run: npm install && npx ng test --watch=false --browsers=ChromeHeadless
      working-directory: ./client

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: flowkeeper
        password: ${{ secrets.DOCKER_APPLICATION_SECRET }}

    - name: Build docker image and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: flowkeeper/flowfrontend:${{ steps.extract_branch.outputs.branch }}
